### PR TITLE
Add GPT-4 Turbo model

### PR DESCRIPTION
**Pull request by alessiomaffeis**
Hi! Thanks for making this extension. :) 

I think it would be nice to support GPT-4 Turbo, now that it's available to anybody that has access to GPT-4.
Bigger context and 3x cheaper: https://openai.com/pricing

I didn't go as far as replacing GPT-4 with it (might not be desirable for some use cases I have not thought about).

### CODE REVIEW

**Review by Cnly — COMMENTED** [review]
Hi @alessiomaffeis, thanks for the PR! From my testing I think this works. But could you also add the new option to the global model list in package.json so it can be used as the default for all commands?

**Comment by alanzchen** [comment]
There's also a `gpt-4-turbo-preview` alias https://openai.com/blog/new-embedding-models-and-api-updates

**Comment by alessiomaffeis** [comment]
> Hi @alessiomaffeis, thanks for the PR! From my testing I think this works. But could you also add the new option to the global model list in package.json so it can be used as the default for all commands?

Ooops, missed it! :) Fixed.

> There's also a `gpt-4-turbo-preview` alias https://openai.com/blog/new-embedding-models-and-api-updates

Good point, changed it!

**Comment by alessiomaffeis** [comment]
~~Sorry, I committed from the web interface and it seems it missed some edits, let me fix it!~~
DONE! :)

**Review by Cnly — APPROVED** [review]
LGTM. Thanks again!

**Comment by alessiomaffeis** [comment]
> LGTM. Thanks again!

Thank You! :)

**Comment by alessiomaffeis** [comment]
@Cnly @alanzchen will you open a PR towards https://github.com/raycast/extensions?

**Comment by alessiomaffeis** [comment]
> @Cnly @alanzchen will you open a PR towards https://github.com/raycast/extensions?

@Cnly @alanzchen ping 😜

**Comment by alanzchen** [comment]
@Cnly Do you have the time to do it? PR to the Raycast Store has been very painful in my experience. @alessiomaffeis I could add you as a maintainer to this repo if you wish.

**Comment by alessiomaffeis** [comment]
> @Cnly Do you have the time to do it? PR to the Raycast Store has been very painful in my experience. @alessiomaffeis I could add you as a maintainer to this repo if you wish.

@alanzchen I also don't have much free time, but I can try! Feel free to add me, if you like.

**Comment by alanzchen** [comment]
@alessiomaffeis Invited. By the way, you probably should be able to PR to Raycast store without access to this repo.

**Pull request merged**
